In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('test_data')

In [5]:
df.head()

,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender,health_condition
0,7.65,75.2,22.98,1881.0,6995.0,50.4,2.33,veg,medium,poor,active,occasional,male,at-risk
1,8.95,74.4,18.57,1940.0,10242.0,32.5,2.29,veg,low,average,active,occasional,male,fit
2,6.86,90.9,23.17,2036.0,5786.0,27.2,2.50,balanced,high,poor,moderate,occasional,other,at-risk
3,6.80,61.2,18.43,2247.0,12669.0,55.3,2.65,balanced,medium,good,moderate,no,male,at-risk
4,8.27,74.7,22.36,2722.0,13482.0,58.0,3.17,veg,high,average,active,occasional,other,at-risk

In [6]:
dummy_data = df.loc[0:3]

In [7]:
dummy_data.head()

,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender,health_condition
0,7.65,75.2,22.98,1881.0,6995.0,50.4,2.33,veg,medium,poor,active,occasional,male,at-risk
1,8.95,74.4,18.57,1940.0,10242.0,32.5,2.29,veg,low,average,active,occasional,male,fit
2,6.86,90.9,23.17,2036.0,5786.0,27.2,2.50,balanced,high,poor,moderate,occasional,other,at-risk
3,6.80,61.2,18.43,2247.0,12669.0,55.3,2.65,balanced,medium,good,moderate,no,male,at-risk

In [8]:
dummy_data.to_csv("script_data", index=False)